auto_save: false
display_label_popup: false
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: null
label_flags: null
labels: { 'none', 'building', 'road', 'street', 'plastic_house', 'farmland', 'forest', 'waterside'}
file_search: null
sort_labels: false
validate_label: null

default_shape_color: [255, 0, 204]
shape_color: 'manual'
shift_auto_shape_color: 0
label_colors: { 'none': [0, 0, 0],
                'building': [255, 0, 0],
                'road': [255, 255, 0],
                'street': [ 150, 150, 0 ],
                'plastic_house': [255, 150, 0],
                'farmland': [0, 0, 255],
                'forest': [0, 255, 0],
                'waterside': [0, 255, 255] }

shape:
  # drawing
  line_color: [255, 0, 204, 128]
  fill_color: [255, 0, 204, 60]  # transparent
  vertex_fill_color: [255, 0, 204, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]

# main
flag_dock:
  show: false
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: false
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  open_dir_json: Ctrl+J
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [Ctrl+Shift+D]
  open_prev: [Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: W
  create_rectangle: null
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: E
  show_preview: V
  delete_polygon: S
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: A
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  class_none : F1
  class_building : F2
  class_road : F3
  class_street : F4
  class_plastic_house : F5
  class_farmland : F6
  class_forest : F7
  class_waterside : F8
